# Write a Python program to print the documents (syntax, description etc.) of Python built-in function(s).
print(print.__doc__)
print('')
print(len.__doc__)
print('')
print(abs.__doc__)
print('')
print(list().__doc__)
print('')
print(tuple().__doc__)
print('')
print(dict.__doc__)
print('')
print(set.__doc__)
print('')
print(range.__doc__)